apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aplicacion-webapp-deployment
  namespace: proyecto6

spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: aplicacion-webapp
    spec:
      containers:
      - name: aplicacion-webapp
        image: jloaiz16/proyecto2:1.0

        ports:
        - name: nodejs-port
          containerPort: 3000
      - name: api-nginx
      #1.13.8
        image: nginx:1.13.9
        ports:
        - name: http-port
          containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: config-volume
        configMap:
          name: webapp-nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf